{% set name = "coderedcms" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coderedcms-{{ version }}.tar.gz
  sha256: a1873256eb829071875332d9ff5089c090f95facd78e1d85dac7e20be35cedf9

build:
  entry_points:
    - coderedcms=coderedcms.bin.coderedcms:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.8,<4.13
    - django-eventtools ==1.0.*
    - django-bootstrap5 ==24.3
    - django >=4.2,<6.0
    - geocoder ==1.38.*
    - icalendar ==6.0.*
# icalendar 6.0.1 requires tzdata, which is not installed
    - tzdata
    - wagtail >=6.3,<7.0
    - wagtail-cache >=2.4,<3
    - wagtail-seo >=2.5,<3

test:
  imports:
    - coderedcms
  commands:
    - pip check
    - coderedcms help
  requires:
    - python {{ python_min }}  
    - pip

about:
  home: https://github.com/coderedcorp/coderedcms
  summary: Wagtail-based CMS by CodeRed for building marketing websites.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE.txt
    - coderedcms/wagtail_flexible_forms/LICENSE
    - coderedcms/static/coderedcms/vendor/bootstrap/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
