{% set name = "coderedcms" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coderedcms-{{ version }}.tar.gz
  sha256: df7e86bcf4c4bcc054754aa5d9d0424ffcec5018d5533e65fabfc106788da2a8

build:
  entry_points:
    - coderedcms=coderedcms.bin.coderedcms:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4 >=4.8,<4.12
    - django-eventtools ==1.0.*
    - django-bootstrap5 ==23.3
    - django >=4.1,<5.1
    - geocoder ==1.38.*
    - icalendar ==5.0.*
    - wagtail >=5.0,<6.0
    - wagtail-cache >=2.3,<3
    - wagtail-seo >=2.4,<3

test:
  imports:
    - coderedcms
  commands:
    - pip check
    - coderedcms help
  requires:
    - pip

about:
  home: https://github.com/coderedcorp/coderedcms
  summary: Wagtail-based CMS by CodeRed for building marketing websites.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - coderedcms/wagtail_flexible_forms/LICENSE
    - coderedcms/static/coderedcms/vendor/bootstrap/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
